#sudo: required
language: java
jdk: 
    - openjdk11
env:
        - NODE_VERSION=12 CC=clang CXX=clang++
services:
    - docker
branches:
    only:
    - master
    except:
    - dev 
# env:
#     global:
#       - SHA=$(git rev-parse HEAD)
 
before_install:   
    - nvm install $NODE_VERSION  
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # - cd dit-spring-boot-project

before_script:
    - cd HuntAbode
    - npm install 
    - npm run build --prod 
    - cd .. 
    - mv HuntAbode/dist/argon-design-system-angular/* RentalApplication/src/main/resources/static 
    - cd RentalApplication
script:
- mvn clean install -DskipTests
